"use strict";
const STORAGE_KEY="penarrubia.communities.v1";
const seed=[{id:crypto.randomUUID(),name:"Residencial Peñarrubia",nif:"H28654321",address:"Calle de la Sierra, 14",city:"Madrid",province:"Madrid",postalCode:"28035",phone:"912 345 678",email:"contacto@penarrubia.es",notes:""},{id:crypto.randomUUID(),name:"Edificio Los Olivos",nif:"H19456789",address:"Avenida de Europa, 6",city:"Pozuelo de Alarcón",province:"Madrid",postalCode:"28224",phone:"913 456 789",email:"",notes:"Próxima junta ordinaria en octubre."}];
let communities=load(),editingId=null,deletingId=null;const list=document.querySelector("#community-list"),empty=document.querySelector("#empty-state"),count=document.querySelector("#result-count"),search=document.querySelector("#search"),form=document.querySelector("#community-form"),dialog=document.querySelector("#community-dialog"),deleteDialog=document.querySelector("#delete-dialog");
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:seed}catch{return seed}}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(communities))}function filtered(){const q=search.value.trim().toLocaleLowerCase("es");return communities.filter(c=>[c.name,c.nif,c.city,c.address].some(v=>v.toLocaleLowerCase("es").includes(q)))}function button(label,action,extra=""){const b=document.createElement("button");b.type="button";b.className=`text-button ${extra}`;b.textContent=label;b.addEventListener("click",action);return b}
function render(){const items=filtered();list.replaceChildren();items.forEach(c=>{const row=document.createElement("tr"),fields=[[c.name,c.notes,"community-name"],[c.nif],[c.address],[`${c.city}, ${c.province}`],[c.phone||c.email||"—"]];fields.forEach(([value,secondary,className])=>{const td=document.createElement("td"),primary=document.createElement("span");primary.textContent=String(value??"");if(className)primary.className=className;td.append(primary);if(secondary){const note=document.createElement("span");note.className="community-notes";note.textContent=String(secondary);td.append(note)}row.append(td)});const actions=document.createElement("td");actions.className="row-actions";actions.append(button("Editar",()=>openEditor(c.id)),button("Eliminar",()=>openDelete(c.id),"delete"));row.append(actions);list.append(row)});empty.hidden=items.length!==0;count.textContent=`${items.length} ${items.length===1?"comunidad":"comunidades"}`}
function openEditor(id=null){editingId=id;form.reset();document.querySelector("#form-error").textContent="";const c=communities.find(item=>item.id===id);document.querySelector("#dialog-title").textContent=c?"Editar comunidad":"Nueva comunidad";if(c)Object.entries(c).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value});dialog.showModal();form.elements.name.focus()}function closeEditor(){dialog.close();editingId=null}function openDelete(id){deletingId=id;const c=communities.find(item=>item.id===id);document.querySelector("#delete-message").textContent=`Vas a eliminar “${c.name}”. Esta acción no se puede deshacer.`;deleteDialog.showModal()}function toast(message){const el=document.querySelector("#toast");el.textContent=message;el.classList.add("visible");window.setTimeout(()=>el.classList.remove("visible"),2800)}
form.addEventListener("submit",event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));["name","nif","address","city","province","postalCode","email"].forEach(k=>data[k]=data[k].trim());data.nif=data.nif.toUpperCase();const error=document.querySelector("#form-error");if(!form.checkValidity()){error.textContent="Revisa los campos obligatorios y el formato de NIF y código postal.";form.reportValidity();return}if(data.email&&!/^\S+@\S+\.\S+$/.test(data.email)){error.textContent="Introduce un correo electrónico válido.";return}if(communities.some(c=>c.nif===data.nif&&c.id!==editingId)){error.textContent="Ya existe una comunidad con ese NIF.";return}if(editingId){communities=communities.map(c=>c.id===editingId?{...data,id:editingId}:c);toast("Comunidad actualizada.")}else{communities.unshift({...data,id:crypto.randomUUID()});toast("Comunidad creada.")}save();closeEditor();render()});
document.querySelector("#new-community").addEventListener("click",()=>openEditor());document.querySelector("#close-dialog").addEventListener("click",closeEditor);document.querySelector("#cancel-dialog").addEventListener("click",closeEditor);document.querySelector("#confirm-delete").addEventListener("click",()=>{communities=communities.filter(c=>c.id!==deletingId);save();render();toast("Comunidad eliminada.");deletingId=null});search.addEventListener("input",render);render();
