"use strict";
const STORAGE_KEY="penarrubia.communities.v1";
const PROVINCES={"01":"Álava","02":"Albacete","03":"Alicante","04":"Almería","05":"Ávila","06":"Badajoz","07":"Illes Balears","08":"Barcelona","09":"Burgos","10":"Cáceres","11":"Cádiz","12":"Castellón","13":"Ciudad Real","14":"Córdoba","15":"A Coruña","16":"Cuenca","17":"Girona","18":"Granada","19":"Guadalajara","20":"Gipuzkoa","21":"Huelva","22":"Huesca","23":"Jaén","24":"León","25":"Lleida","26":"La Rioja","27":"Lugo","28":"Madrid","29":"Málaga","30":"Murcia","31":"Navarra","32":"Ourense","33":"Asturias","34":"Palencia","35":"Las Palmas","36":"Pontevedra","37":"Salamanca","38":"Santa Cruz de Tenerife","39":"Cantabria","40":"Segovia","41":"Sevilla","42":"Soria","43":"Tarragona","44":"Teruel","45":"Toledo","46":"Valencia","47":"Valladolid","48":"Bizkaia","49":"Zamora","50":"Zaragoza","51":"Ceuta","52":"Melilla"};
const seed=[{id:crypto.randomUUID(),name:"Residencial Peñarrubia",nif:"H28654321",address:"Calle de la Sierra, 14",city:"Madrid",province:"Madrid",postalCode:"28035",phone:"912345678",otherPhone:"913456789",email:"contacto@penarrubia.es",notes:""},{id:crypto.randomUUID(),name:"Edificio Los Olivos",nif:"H19456789",address:"Avenida de Europa, 6",city:"Pozuelo de Alarcón",province:"Madrid",postalCode:"28224",phone:"913456789",otherPhone:"914567890",email:"contacto@penarrubia.es",notes:"Próxima junta ordinaria en octubre."}];
let communities=load(),editingId=null,deletingId=null,locations=[],locationsById=new Map(),postalIndex=new Map();
const list=document.querySelector("#community-list"),empty=document.querySelector("#empty-state"),count=document.querySelector("#result-count"),search=document.querySelector("#search"),form=document.querySelector("#community-form"),dialog=document.querySelector("#community-dialog"),deleteDialog=document.querySelector("#delete-dialog"),error=document.querySelector("#form-error"),nifInput=form.elements.nif,phoneInput=form.elements.phone,otherPhoneInput=form.elements.otherPhone,emailInput=form.elements.email,citySelect=form.elements.city,provinceSelect=form.elements.province,postalCodeInput=form.elements.postalCode;
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:seed}catch{return seed}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(communities))}
function filtered(){const q=search.value.trim().toLocaleLowerCase("es");return communities.filter(c=>[c.name,c.nif,c.city,c.address].some(v=>v.toLocaleLowerCase("es").includes(q)))}
function button(label,action,extra=""){const b=document.createElement("button");b.type="button";b.className=`text-button ${extra}`;b.textContent=label;b.addEventListener("click",action);return b}
function render(){const items=filtered();list.replaceChildren();items.forEach(c=>{const row=document.createElement("tr"),fields=[[c.name,c.notes,"community-name"],[c.nif],[c.address],[`${c.city}, ${c.province}`],[c.phone||c.email||"—"]];fields.forEach(([value,secondary,className])=>{const td=document.createElement("td"),primary=document.createElement("span");primary.textContent=String(value??"");if(className)primary.className=className;td.append(primary);if(secondary){const note=document.createElement("span");note.className="community-notes";note.textContent=String(secondary);td.append(note)}row.append(td)});const actions=document.createElement("td");actions.className="row-actions";actions.append(button("Editar",()=>openEditor(c.id)),button("Eliminar",()=>openDelete(c.id),"delete"));row.append(actions);list.append(row)});empty.hidden=items.length!==0;count.textContent=`${items.length} ${items.length===1?"comunidad":"comunidades"}`}
function addPlaceholder(select,text){select.replaceChildren(new Option(text,""));}
function selectCommunity(city,province){const match=locations.find(location=>location.name===city&&location.province===province)||locations.find(location=>location.name===city);if(match)citySelect.value=match.id;}
function populateLocations(data){locations=Object.entries(data).map(([id,value])=>({id,name:value.nombre,province:PROVINCES[id.slice(0,2)],postalCodes:value.codigos_postales})).filter(location=>location.province).sort((a,b)=>a.name.localeCompare(b.name,"es")||a.province.localeCompare(b.province,"es"));locationsById=new Map(locations.map(location=>[location.id,location]));postalIndex=new Map();locations.forEach(location=>location.postalCodes.forEach(postalCode=>{const matches=postalIndex.get(postalCode)||[];matches.push(location);postalIndex.set(postalCode,matches)}));addPlaceholder(citySelect,"Selecciona un municipio");locations.forEach(location=>citySelect.add(new Option(`${location.name} (${location.province})`,location.id)));citySelect.disabled=false;addPlaceholder(provinceSelect,"Selecciona una provincia");Object.values(PROVINCES).sort((a,b)=>a.localeCompare(b,"es")).forEach(province=>provinceSelect.add(new Option(province,province)));provinceSelect.disabled=false;if(dialog.open){const editing=communities.find(community=>community.id===editingId);if(editing)selectCommunity(editing.city,editing.province);else syncFromPostalCode();}}
function loadLocations(){if(window.MUNICIPIOS_INE){populateLocations(window.MUNICIPIOS_INE);return}addPlaceholder(citySelect,"No se pudieron cargar los municipios");addPlaceholder(provinceSelect,"No se pudieron cargar las provincias");error.textContent="No se ha podido cargar el catálogo territorial. Recarga la página para continuar.";}
function syncFromPostalCode(){const postalCode=postalCodeInput.value,matches=postalIndex.get(postalCode);if(postalCode.length===5&&matches?.length){const location=matches[0];citySelect.value=location.id;provinceSelect.value=location.province;}}
function syncFromCity(){const location=locationsById.get(citySelect.value);if(location){provinceSelect.value=location.province;postalCodeInput.value=location.postalCodes[0]||"";}}
function validateFields(){const nif=nifInput.value.trim().toUpperCase(),phone=phoneInput.value.trim(),otherPhone=otherPhoneInput.value.trim(),email=emailInput.value.trim(),postalCode=postalCodeInput.value.trim();nifInput.value=nif;phoneInput.value=phone;otherPhoneInput.value=otherPhone;emailInput.value=email;nifInput.setCustomValidity(/^H\d{8}$/.test(nif)?"":"El NIF debe comenzar por H y contener 8 dígitos numéricos.");phoneInput.setCustomValidity(/^\d{9}$/.test(phone)?"":"El teléfono debe contener 9 dígitos numéricos.");otherPhoneInput.setCustomValidity(/^\d{9}$/.test(otherPhone)?"":"El otro teléfono debe contener 9 dígitos numéricos.");emailInput.setCustomValidity(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?"":"Introduce una dirección de email válida.");postalCodeInput.setCustomValidity(/^\d{5}$/.test(postalCode)&&postalIndex.has(postalCode)?"":"El código postal debe contener 5 dígitos y corresponder a un código postal de España.");}
function openEditor(id=null){editingId=id;form.reset();error.textContent="";const c=communities.find(item=>item.id===id);document.querySelector("#dialog-title").textContent=c?"Editar comunidad":"Nueva comunidad";if(c){Object.entries(c).forEach(([key,value])=>{if(form.elements[key]&&key!=="city")form.elements[key].value=value});selectCommunity(c.city,c.province)}dialog.showModal();form.elements.name.focus()}
function closeEditor(){dialog.close();editingId=null}
function openDelete(id){deletingId=id;const c=communities.find(item=>item.id===id);document.querySelector("#delete-message").textContent=`Vas a eliminar “${c.name}”. Esta acción no se puede deshacer.`;deleteDialog.showModal()}
function toast(message){const el=document.querySelector("#toast");el.textContent=message;el.classList.add("visible");window.setTimeout(()=>el.classList.remove("visible"),2800)}
form.addEventListener("submit",event=>{event.preventDefault();validateFields();const selectedLocation=locationsById.get(citySelect.value);if(!form.checkValidity()||!selectedLocation){if(nifInput.validationMessage)error.textContent="Hay un error en el campo NIF; corrígelo para continuar.";else if(postalCodeInput.validationMessage)error.textContent="Hay un error en el campo código postal; corrígelo para continuar.";else if(phoneInput.validationMessage)error.textContent="El teléfono debe contener 9 dígitos numéricos.";else if(otherPhoneInput.validationMessage)error.textContent="El otro teléfono debe contener 9 dígitos numéricos.";else if(emailInput.validationMessage)error.textContent="Hay un error en el email de contacto; corrígelo para continuar.";else error.textContent="Revisa los campos obligatorios y sus formatos.";form.reportValidity();return}const data=Object.fromEntries(new FormData(form));["name","nif","address","phone","otherPhone","postalCode","email"].forEach(key=>data[key]=data[key].trim());data.city=selectedLocation.name;data.province=provinceSelect.value;if(communities.some(c=>c.nif===data.nif&&c.id!==editingId)){error.textContent="Ya existe una comunidad con ese NIF.";return}if(editingId){communities=communities.map(c=>c.id===editingId?{...data,id:editingId}:c);toast("Comunidad actualizada.")}else{communities.unshift({...data,id:crypto.randomUUID()});toast("Comunidad creada.")}save();closeEditor();render()});
nifInput.addEventListener("input",()=>{nifInput.value=nifInput.value.toUpperCase();nifInput.setCustomValidity("");});[phoneInput,otherPhoneInput].forEach(input=>input.addEventListener("input",()=>{input.value=input.value.replace(/\D/g,"");input.setCustomValidity("");}));emailInput.addEventListener("input",()=>emailInput.setCustomValidity(""));postalCodeInput.addEventListener("input",()=>{postalCodeInput.value=postalCodeInput.value.replace(/\D/g,"").slice(0,5);postalCodeInput.setCustomValidity("");syncFromPostalCode();});citySelect.addEventListener("change",syncFromCity);document.querySelector("#new-community").addEventListener("click",()=>openEditor());document.querySelector("#close-dialog").addEventListener("click",closeEditor);document.querySelector("#cancel-dialog").addEventListener("click",closeEditor);document.querySelector("#confirm-delete").addEventListener("click",()=>{communities=communities.filter(c=>c.id!==deletingId);save();render();toast("Comunidad eliminada.");deletingId=null});search.addEventListener("input",render);render();loadLocations();
